### ISSUE TITLE
Unable to create GH branches from Jira issue

### ISSUE THREAD

**Issue by rfriedel** [atlassian/github-for-jira#1845]
We have integrated 4 of our GitHub (cloud) organizations with our "jciproducts" Jira instance.

The GitHub configuration page shows that all 4 organizations have been configured and the backfill status shows "finished".

When we try to create a new GitHub branch through the GitHub panel from a new Jira issue - we can only see a very limited number of repos (less than 50, where we should have thousands to choose from).

I have tried to enter the repo name via "org/repo" nomenclature, but had no success .. it seems the only repos that are being found are the limited number of repos that are being shown pre-populated when I select the down arrow on that Repository selection via 'Create Branch' > 'Repository'.

I have verified on the GitHub side, that the 'github-for-jira' app was configured for "all" repos (on all 4 orgs).

How can we use this integration for all repos?

-Rudi.

Ps. going the other route, i.e. adding the Jira issue key on GH commits seems to integrate just fine - it's the path coming from Jira that doesn't seem to work properly

(adding @anadivats for visibility)

**Comment by uskpea** [comment]
I have the same problem when I created the branches and the list of repositories have a small pre-list but cannot search to the GitHub organization of all the repositories in Search. The Seach loops and unable to find any other repositories outside of the list.
![image](https://user-images.githubusercontent.com/88337031/214072319-41b90836-682a-4e14-ac2d-5e2be148935c.png)

**Comment by imirandad** [comment]
:( same issue here

**Comment by imirandad** [comment]
Same issue here :(

**Comment by qschmick** [comment]
We are also having this issue with our org but it is not impacting everyone. It seems those with Admin rights in Github see all of the repos without issue and others can't search/filter the repos.

**Comment by bgvozdev** [comment]
Hey @rfriedel @uskpea @imirandad @qschmick thanks for your requests and your patience!

We acknowledge the problem and working on a fix. Please stay tuned!

**Comment by bgvozdev** [comment]
Hey @rfriedel @uskpea @imirandad @qschmick , this should be fixed now. Sorry for the inconvenience!

One thing to note though: the list of repos will contain only those that the current GitHub user (that is currently signed in in github.com)  has access to. This is done for a security reasons.

Closing the issue, please feel free to reopen in case you have any other questions/concerns .

**Comment by rfriedel** [comment]
@bgvozdev - is there any reinitializing / reindexing required from our end?  We still do not seem to be able to see all repos (verified that user has r/w permissions on the repo)?
I do see lots of `500` status errors (Developer Tools > network) when I type my desired repo name into the `Create Branch`  GitHub panel .. so something is not looking right.

**Comment by qschmick** [comment]
@bgvozdev Thank you, working for our users now.

**Comment by bgvozdev** [comment]
That's weird @rfriedel , would you mind to provide your jira hostname?

**Comment by bgvozdev** [comment]
Hey @rfriedel , thanks for your patience. We have fixed a bunch of issues with the feature recently, particularly, if a user didn't have access to a single connected org (albeit it might've had access to other orgs), the repo search would fail for them.

Would you mind to give it another go and let us know if this is fixed for you or you still experience issues? Thanks!

**Comment by bgvozdev** [comment]
Hi @rfriedel , sorry to hear that there's still no success. I've checked logs related to your installation once again (for the search repos feature) and still see just permission errors.

Could you please double-check that the user you are currently logged in can find these repos in GitHub at all? It is very easy to do:
1. open the issue view, click on "Create Branch" and enter the search string that presumably should've returned repos you were looking for
2. in a notepad, [construct a search query](https://docs.github.com/en/search-github/searching-on-github/searching-for-repositories) as following: `search-term org:org-name-the-wanted-repo-is-expected-to-be-in org:currently-logged-into-github-username in:name`. For example, in my case, if I'm looking for a repository in `Atlassian` org that has `test` in name, and my currently logged in user is `bgvozdev`. Therefore the search string would be  `test org:Atlassian org:bgvozdev in:name` . That's exactly the query [that the app is using](http://github.com/atlassian/github-for-jira/blob/dcb558dfcac2fc870b9cddb8f31a536a8e0ba77c/src/routes/github/repository/github-repository-get.ts#L73-L73) to ask GitHub for the repos. (Please note that the org must be connected on "GitHub for Jira" admin page, because this is how the org name makes it way into the search string.)
3. encode it using [some online tool ](https://www.url-encode-decode.com/) to convert the search string into a query parameter. In my case, I received `test+org%3AAtlassian+org%3Abgvozdev+in%3Aname`
4. open a new tab and enter the following URL: `https://github.com/search?q=YOUR-ENCODED-SEARCH-STRING-FROM-STEP-3` . For me the resulting string would be `https://github.com/search?q=test+org%3AAtlassian+org%3Abgvozdev+in%3Aname`

Could you please confirm that you are able to find the repos form a connected org you were looking for using this method? Thank you.

**Comment by rfriedel** [comment]
I was "experimenting" with the URL encoded search strings that you explained above.

My initial attempts of finding particular repos on the Atlassian Jira Issue side .. and via GitHub (GH) URL failed equally.  While creating some new test repos I was forced to authenticate to GH via SSO and 2FA, once authenticated I was able to find my test repos from the Jira Issue GH panel and the GH URL.  So the search does require an authenticated user (token) .. so it seems.

This might be problematic on our end as we do have different user credentials for different orgs. We currently have (integrated with) 2 orgs with public managed user accounts (public GH handle) and 2 orgs with Enterprise Managed User (EMU) accounts .. so I always have to switch identities depending on what org I wish to access.

I noticed on my initial repo search from the Jira Issue GH panel, my public GH handle was pre-populated on the top right corner of that screen .. the link underneath `Change GitHub login` does not seem to trigger anything on my end that would allow me to change my user identity.

What should be our next steps, or usage workflow? Looks like we'd need to force an auth user session before we could query anything from the Jira side.

I also noticed that the Backfill displayed data seems to get stale and does not pick up new repos that were added .. until I manually kick of the backfill. I noticed that one of our orgs showed like a 1 year old repo count ..

This might be related.

**Comment by jbparker** [comment]
Hi @bgvozdev - back again... sorry!

After initially having this handled on #1833, we're back to having some users with **Write** access in the GH repository getting `Internal Server Error` when trying to get results back from the following URL that the **Create Branch** page uses:

https://github.atlassian.com/github/create-branch/owners/SomeGitHubOrganization/repos/SomeRepository/branches?jiraHost=https%3A%2F%2Fsomeorg.atlassian.net

We've had the user reauthenticate on both GH and Jira side, but no dice on a fix.

Any chance you can peek in our organization logs and see if we are missing something?

**Comment by gxueatlassian** [comment]
Hi guys, just to give an update we are actively working on this ticket now. So one big problem is user have different credentials for different orgs via SSO, hence the feature is not working as expected. Work around to switch between orgs is not convenience. We are trying to use app token instead of user token to do the thing. But need to sort out some critical path for security purpose first since app token comes with greater power :) 

I don't have an accurate ETA right now, but will try to give an update in two weeks time.

**Comment by shehrozeee** [comment]
So we are facing the same 500 error and for some reason I am able to create a branch in github for one project but not for the other one. I am logged in using the same account and nothing has changed. maybe this helps in debugging the issue. we will also use the workaround suggested above for the time being. The project where I cant create the branches is a migrated project from our on prem installation.

**Comment by shehrozeee** [comment]
One other thing that may help. so It fails to load branches for some repos but if I change the repo to a project that I had created, there is no error. so it may likely related to repo access. however I can create branches in the repos that dont work and I am admin of the github organization too

**Comment by arabold** [comment]
Got the 500 error as well. I'm able to select the repository from my org, but it doesn't find a valid branch:
<img width="541" alt="jira-github-issue" src="https://user-images.githubusercontent.com/1548229/234968618-bb4a2099-b6ac-40fc-ad54-25c8e29e3bdd.png">

My suspicion is that this is somehow related to us using an Enterprise account (but with GitHub Cloud, not self-hosted) and the repository being owned by an Organization in this Enterprise account. I'm owner for bot the org and the enterprise.

**Comment by shehrozeee** [comment]
I am able to load branches of some of the repos and unable to do so for the
others. All these repos are in a GitHub organization account and I am the
owner of the gh organization.

**Comment by JaronFrenk** [comment]
We have this issue as well. We can find the repositories, but we cannot fetch the branches. We had a trial account, and now have a  paying enterprise account since last week. We have changed nothing with regards to authorization. No new users have been added.

**Comment by bhorrock** [comment]
<img width="532" alt="image" src="https://user-images.githubusercontent.com/2085418/235305830-cf99b91c-7f6d-41be-bc58-6c3be0e473aa.png">
Having the same issue

**Comment by hasi-b** [comment]
> <img alt="image" width="532" src="https://user-images.githubusercontent.com/2085418/235305830-cf99b91c-7f6d-41be-bc58-6c3be0e473aa.png">
> 
> Having the same issue

I am also having the same issue. we could make branches under the github organizations before. we have other projects under the same organizations and connected with jira, which we can create new branches from. But for some reason, can't make new branches.

**Comment by igor9silva** [comment]
Just as a feedback, I did reconnect (disconnect and re-allowed) the GitHub Account (from within Jira global app admin) and **it solved.**

**Possible cause:** we'd recently upgraded from a trial plan to a paid one through an Atlassian partner. That's my best guess based on other comments.

**Comment by JaronFrenk** [comment]
Yes, that did the trick for me as well. Same setup: from trial to paid plan. Just reconnected, and now it works again.

**Comment by rfriedel** [comment]
@bgvozdev , @gxueatlassian - the behavior has improved noticeably, thank you.  I am able to find any repo (with updates created after last backfill start date) across our GHEC and GH EMU orgs (different user credentials). We have to run more in-depth testing for branch creation/association but so far this looks very promising.

**Comment by christiankohl-CV** [comment]
We had the same issues around being able to select the repos but then get the error when it tries to load the branches

I disconnected/uninstalled the JIRA app from GitHub and then reinitatied the connection from JIRA and now the integration and branch creation is working again.

Still unsure as to what caused it to stop working as a week or so ago we did not have this issue.

**Comment by emilg** [comment]
Same problem here. About a week ago, the developers noticed that you could no longer make branches through jira.

We had to uninstall github for jira and then reinstall it. And now everything works as it should.
Would have been nice if this hadn't been needed.

**Comment by gxueatlassian** [comment]
> +1
> 
> I also uninstalled and installed Github for Jira, but I still get the 'Create branch link expired' error..
> 
> The issue started happening to us today. Any updates?

Hi this should be fixed now. Can you try again? Thanks.

**Comment by product-nick** [comment]
> > +1
> > I also uninstalled and installed Github for Jira, but I still get the 'Create branch link expired' error..
> > The issue started happening to us today. Any updates?
> 
> Hi this should be fixed now. Can you try again? Thanks.

Works now. Thanks :)

**Comment by joshkay10** [comment]
We have added additional changes that should [support this issue](https://github.com/atlassian/github-for-jira/pull/2332) , hopefully this resolves any outstanding problems for this particular problem :)
